# Configuration settings for sensor reading apps

# Options related to sending data to a local file
record:
    enabled: true
    file: sensordata.csv
    daily: true

# Options related to sending data to remore server in real-time
cloud:
    enabled: true
    host:
    port:
    dbname: house
    dbuser:
    dbpwd:

# Plotting options
display:
    enabled: false
    subplots: 2
    window: 10

# Logging options
logs:
    file: service.log
    level: debug
