# This file is part of home sesnors project.
# Copyright (c) 2017, Guy Kemeber, Samer Mansour, and Maen Artimy


# Configuration settings for sensor reading apps

# Sensor details
# sensor names are case sensitive
sensors:
    DHT:
        - temperature
        - humidity
    acc:
        - x
        - y
        - z

# Options related to sending data to a local file
record:
    enabled: true
    format: influx              # or csv
    file: /home/pi/sensordata/sensordata.csv        # the extension will be ignored
    daily: true                 # recommended       
        
# Options related to sending data to remore server in real-time
cloud:
    enabled: false          # this affects real-time only
    host: 192.168.2.31
    port: 8086
    dbname: house
    patch: 50
    retries: 3

# Plotting options
display:
    enabled: false
    subplots: 2
    window: 10

# Logging options
logs:
    file: service.log
    level: info

